version: '3.7'

services:
  db:
    image: "postgres:9"
    ports: 
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: pgpassword
      PGDATA: /var/lib/postgresql/data/pgdata
  api:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app
    links:
      - db
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"
  