[development]
address = "localhost"
port = 3000
workers = [number_of_cpus * 2]
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = [number_of_cpus * 2]
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = [number_of_cpus * 2]
log = "critical"
limits = { forms = 32768 }