[development]
address = "0.0.0.0"
port = 3000
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
limits = { forms = 32768 }